import { Routes } from '@angular/router';

const placeholder = () => import('./shared/pages/placeholder-page/placeholder-page').then((c) => c.PlaceholderPageComponent);

export const routes: Routes = [
  { path: '', pathMatch: 'full', loadComponent: () => import('./pages/home/home').then((c) => c.HomeComponent), data: { seo: { title: 'Terreta | Software, Automatización e IA para Empresas', description: 'Desarrollamos software a medida, aplicaciones web, apps móviles, automatizaciones e inteligencia artificial para empresas que quieren crecer con tecnología clara, moderna y útil.', canonicalPath: '/', image: 'https://realterretaia.com/assets/brand/terreta-logo.png' } } },
  { path: 'servicios', loadComponent: () => import('./pages/services/services').then((c) => c.ServicesComponent), data: { seo: { title: 'Servicios Digitales | Apps, Automatización e IA | Terreta', description: 'Soluciones web, móviles, automatizaciones e inteligencia artificial adaptadas a las necesidades reales de cada empresa.', canonicalPath: '/servicios' } } },
  { path: 'aplicaciones/fitness-app', loadComponent: placeholder, data: { eyebrow: 'Elite Coach', heading: 'La app que profesionaliza tu negocio fitness', summary: 'Una plataforma para organizar rutinas, seguimiento, nutrición y clientes.', seo: { title: 'Elite Coach App | Aplicación Fitness Desarrollada por Terreta', description: 'Plataforma digital para entrenadores, clientes y centros deportivos desarrollada por Terreta.', canonicalPath: '/aplicaciones/fitness-app' } } },
  { path: 'outsourcing', loadComponent: placeholder, data: { eyebrow: 'IT-Outsourcing', heading: 'IT-Outsourcing', summary: 'Esta página se reconstruirá en una próxima fase manteniendo el contenido verificado de la web actual.', seo: { title: 'IT-Outsourcing | Terreta', description: 'Servicios de IT-Outsourcing de Terreta.', canonicalPath: '/outsourcing' } } },
  { path: 'como-trabajamos', loadComponent: placeholder, data: { eyebrow: 'Metodología', heading: 'Cómo trabajamos en Terreta', summary: 'Planificación, flexibilidad y seguimiento continuo para avanzar con orden y visibilidad.', seo: { title: 'Cómo Trabajamos | Desarrollo de Software y Automatización | Terreta', description: 'Conoce la metodología de Terreta para desarrollar proyectos con planificación, hitos, validación y seguimiento continuo.', canonicalPath: '/como-trabajamos' } } },
  { path: 'nosotros', loadComponent: placeholder, data: { eyebrow: 'Terreta', heading: 'Nosotros', summary: 'Soluciones tecnológicas útiles, escalables y sostenibles para empresas y profesionales.', seo: { title: 'Nosotros | Terreta Software, IA y Automatización', description: 'Conoce el enfoque cercano, flexible y orientado a negocio de Terreta.', canonicalPath: '/nosotros' } } },
  { path: 'contacto', loadComponent: placeholder, data: { eyebrow: 'Contacto', heading: 'Hablemos de tu proyecto', summary: 'El formulario se incorporará en una próxima misión sin añadir todavía infraestructura backend.', seo: { title: 'Contacto | Terreta', description: 'Contacta con Terreta para hablar sobre software a medida, automatización o inteligencia artificial aplicada al negocio.', canonicalPath: '/contacto' } } },
  { path: 'privacy-policy', loadComponent: placeholder, data: { eyebrow: 'Legal', heading: 'Política de privacidad', summary: 'El contenido legal vigente se trasladará sin modificaciones sustanciales en una próxima misión.', seo: { title: 'Política de Privacidad | Terreta', description: 'Política de privacidad y protección de datos de Terreta.', canonicalPath: '/privacy-policy' } } },
  { path: '**', loadComponent: () => import('./pages/not-found/not-found').then((c) => c.NotFoundComponent), data: { seo: { title: 'Página no encontrada | Terreta', description: 'La página solicitada no está disponible.', noIndex: true } } },
];
